#define DEFAULT_SCHEDULED_TICK_OFFSET 20
#define DEFAULT_NODE_PORT 21841
#define DEFAULT_NODE_IP "127.0.0.1"
#define NUMBER_OF_TRANSACTIONS_PER_TICK 1024
#define SIGNATURE_SIZE 64
#define SPECTRUM_DEPTH 24 // Is derived from SPECTRUM_CAPACITY (=N)
#define DEFAULT_SEED "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#define QX_ADDRESS "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMID"
#define ARBITRATOR "AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ"
#define NUMBER_OF_COMPUTORS 676
#define EXCHANGE_PUBLIC_PEERS 0
#define BROADCAST_COMPUTORS 2
#define BROADCAST_FUTURE_TICK_DATA 8
#define REQUEST_COMPUTORS 11
#define REQUEST_TICK_DATA 16
#define BROADCAST_TRANSACTION 24
#define REQUEST_CURRENT_TICK_INFO 27
#define RESPOND_CURRENT_TICK_INFO 28
#define REQUEST_TICK_TRANSACTIONS 29
#define REQUEST_ENTITY 31
#define RESPOND_ENTITY 32
#define PROCESS_SPECIAL_COMMAND 255
#define REQUEST_ISSUED_ASSETS 36
#define RESPOND_ISSUED_ASSETS 37
#define REQUEST_OWNED_ASSETS 38
#define RESPOND_OWNED_ASSETS 39
#define REQUEST_POSSESSED_ASSETS 40
#define RESPOND_POSSESSED_ASSETS 41


#define QX_CONTRACT_INDEX 1
#define QX_FEE_FUNCTION_INDEX 1